// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Domain.Entities.Common;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entities;

public partial class User : Entity
{
    public string UserId { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string ProfileUrl { get; set; }
    public string Email { get; set; }
    public string PhoneNumber { get; set; }
    public string Language { get; set; }

    [NotMapped]
    public virtual User CreatedByNavigation { get; set; }
    [NotMapped]
    public virtual ICollection<User> InverseCreatedByNavigations { get; set; } = new List<User>();
    [NotMapped]
    public virtual User ModifiedByNavigation { get; set; }
    [NotMapped]
    public virtual ICollection<User> InverseModifiedByNavigations { get; set; } = new List<User>();
}